---
apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: jupyterhub
deploy:
  helm:
    releases:
      - createNamespace: true
        name: jupyterhub
        namespace: jupyterhub
        remoteChart: jupyterhub
        repo: https://jupyterhub.github.io/helm-jupyterhub/
        skipBuildDependencies: true
        valuesFiles:
          - overrides.yaml
        version: 1.2.0
