---
apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: keycloak
deploy:
  helm:
    releases:
      - createNamespace: true
        name: keycloak
        namespace: keycloak
        remoteChart: keycloak
        repo: https://charts.bitnami.com/bitnami
        skipBuildDependencies: true
        valuesFiles:
          - overrides.yaml
        version: 9.2.7
